services:
  postgres_db:
    image: postgres:16.3-alpine3.20
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - my_network
    restart: always

  myfastapi:
    build: ./
    env_file:
      - .env
    environment:
      - db_host=postgres_db
    ports:
      - 80:8000
    networks:
      - my_network
    depends_on:
      - postgres_db
    restart: always
    entrypoint: ./init.sh

networks:
  my_network:
    driver: bridge