"""update table

Revision ID: b0857cfdbbfa
Revises: 220dd6714db5
Create Date: 2024-07-05 19:48:06.219852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0857cfdbbfa'
down_revision: Union[str, None] = '220dd6714db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column(
        'country', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'country')
    # ### end Alembic commands ###
